-- Crear la tabla productos
CREATE TABLE productos (
    id BIGINT(20) UNSIGNED PRIMARY KEY NOT NULL,
    nombre VARCHAR(255) NOT NULL CHECK (octet_length(TRIM(nombre)) > 0),
    precio DECIMAL(4,2) NOT NULL CHECK (precio >= 0.01),
    imagen VARCHAR(255) NOT NULL CHECK (
        octet_length(TRIM(imagen)) > 4 
        AND imagen REGEXP '^[0-9a-zA-Z_áéíóúñÑ]+\.(png|jpg|webp|svg|gif)$'
    )
);

-- Insertar los productos
INSERT INTO productos (id, nombre, precio, imagen) VALUES
(1, 'Empanadas de Pollo', 2.01, 'empanadas_de_pollo.jpg'),
(2, 'Pimienta Negra', 3.29, 'pimienta_negra.jpg'),
(3, 'Papas Chips', 3.37, 'papas_chips.jpg'),
(4, 'Yogurt Natural', 3.09, 'yogurt_natural.jpg'),
(5, 'Sopa de Pollo', 2.65, 'sopa_de_pollo.jpg'),
(6, 'Chiles Jalapeños', 5.08, 'chiles_jalapeños.jpg'),
(7, 'Pan de Centeno', 3.89, 'pan_de_centeno.jpg'),
(8, 'Refresco Cola', 4.76, 'refresco_cola.jpg'),
(9, 'Cereal Multigrano', 2.59, 'cereal_multigrano.jpg'),
(10, 'Nuez Pecana', 4.13, 'nuez_pecana.jpg'),
(11, 'Pizza Individual', 3.56, 'pizza_individual.jpg'),
(12, 'Granizado de Café', 4.84, 'granizado_de_café.jpg'),
(13, 'Jamón de Pavo', 3.13, 'jamón_de_pavo.jpg'),
(14, 'Tomates', 3.44, 'tomates.jpg'),
(15, 'Jamón de Pavo', 1.61, 'jamón_de_pavo.jpg'),
(16, 'Arena para Gato', 2.25, 'arena_para_gato.jpg'),
(17, 'Licuado de Plátano', 4.59, 'licuado_de_plátano.jpg'),
(18, 'Cepillo de Dientes', 1.5, 'cepillo_de_dientes.jpg'),
(19, 'Manzanas', 4.93, 'manzanas.jpg'),
(20, 'Panquecitos', 2.75, 'panquecitos.jpg'),
(21, 'Panquecitos', 4.52, 'panquecitos.jpg'),
(22, 'Galletas Saladas', 1.38, 'galletas_saladas.jpg'),
(23, 'Chiles Secos', 1.39, 'chiles_secos.jpg'),
(24, 'Yogurt Natural', 2.33, 'yogurt_natural.jpg'),
(25, 'Crema Dental', 2.04, 'crema_dental.jpg'),
(26, 'Jabón de Barra', 2.08, 'jabón_de_barra.jpg'),
(27, 'Pizza Congelada', 3.35, 'pizza_congelada.jpg'),
(28, 'Helado de Vainilla', 5.34, 'helado_de_vainilla.jpg'),
(29, 'Desodorante', 4.62, 'desodorante.jpg'),
(30, 'Papas Chips', 4.51, 'papas_chips.jpg'),
(31, 'Croquetas para Perro', 1.99, 'croquetas_para_perro.jpg'),
(32, 'Té Negro', 4.72, 'té_negro.jpg'),
(33, 'Huevos', 3.02, 'huevos.jpg'),
(34, 'Servilletas', 2.74, 'servilletas.jpg'),
(35, 'Suavizante de Ropa', 2.17, 'suavizante_de_ropa.jpg'),
(36, 'Cepillo de Dientes', 1.15, 'cepillo_de_dientes.jpg'),
(37, 'Canela en Polvo', 3.45, 'canela_en_polvo.jpg'),
(38, 'Refresco de Lima', 4.59, 'refresco_de_lima.jpg'),
(39, 'Salsa Soya', 2.11, 'salsa_soya.jpg'),
(40, 'Agua de Coco', 2.07, 'agua_de_coco.jpg'),
(41, 'Cloro', 4.41, 'cloro.jpg'),
(42, 'Suavizante de Ropa', 1.02, 'suavizante_de_ropa.jpg'),
(43, 'Tomates', 3.69, 'tomates.jpg'),
(44, 'Chiles Jalapeños', 4.44, 'chiles_jalapeños.jpg'),
(45, 'Refresco de Lima', 3.39, 'refresco_de_lima.jpg'),
(46, 'Pimienta Negra', 2.27, 'pimienta_negra.jpg'),
(47, 'Bebida de Almendra', 3.92, 'bebida_de_almendra.jpg'),
(48, 'Pizza Congelada', 1.42, 'pizza_congelada.jpg'),
(49, 'Leche Entera', 1.41, 'leche_entera.jpg'),
(50, 'Papas Congeladas', 5.46, 'papas_congeladas.jpg'),
(51, 'Café Molido', 3.25, 'cafe_molido.jpg'),
(52, 'Harina de Trigo', 2.15, 'harina_de_trigo.jpg'),
(53, 'Azúcar Morena', 1.89, 'azucar_morena.jpg'),
(54, 'Aceite de Oliva', 4.75, 'aceite_de_oliva.jpg'),
(55, 'Leche Deslactosada', 2.45, 'leche_deslactosada.jpg'),
(56, 'Queso Manchego', 3.99, 'queso_manchego.jpg'),
(57, 'Mantequilla', 2.79, 'mantequilla.jpg'),
(58, 'Pan Integral', 2.99, 'pan_integral.jpg'),
(59, 'Cereal de Chocolate', 3.49, 'cereal_de_chocolate.jpg'),
(60, 'Galletas de Avena', 1.99, 'galletas_de_avena.jpg'),
(61, 'Jugo de Naranja', 3.15, 'jugo_de_naranja.jpg'),
(62, 'Atún en Lata', 2.35, 'atun_en_lata.jpg'),
(63, 'Sardinas', 1.75, 'sardinas.jpg'),
(64, 'Arroz Integral', 2.25, 'arroz_integral.jpg'),
(65, 'Frijoles Negros', 1.95, 'frijoles_negros.jpg'),
(66, 'Lentejas', 2.05, 'lentejas.jpg'),
(67, 'Pasta Espagueti', 1.85, 'pasta_espagueti.jpg'),
(68, 'Salsa de Tomate', 2.55, 'salsa_de_tomate.jpg'),
(69, 'Mayonesa', 3.05, 'mayonesa.jpg'),
(70, 'Mostaza', 1.75, 'mostaza.jpg'),
(71, 'Ketchup', 2.15, 'ketchup.jpg'),
(72, 'Vinagre Blanco', 1.95, 'vinagre_blanco.jpg'),
(73, 'Sal de Mesa', 0.99, 'sal_de_mesa.jpg'),
(74, 'Pimienta Blanca', 2.49, 'pimienta_blanca.jpg'),
(75, 'Canela Entera', 1.89, 'canela_entera.jpg'),
(76, 'Clavos de Olor', 2.15, 'clavos_de_olor.jpg'),
(77, 'Orégano', 1.75, 'oregano.jpg'),
(78, 'Laurel', 1.55, 'laurel.jpg'),
(79, 'Cilantro Fresco', 0.99, 'cilantro_fresco.jpg'),
(80, 'Perejil', 0.89, 'perejil.jpg'),
(81, 'Cebolla Blanca', 1.25, 'cebolla_blanca.jpg'),
(82, 'Ajo', 1.15, 'ajo.jpg'),
(83, 'Zanahorias', 1.35, 'zanahorias.jpg'),
(84, 'Papas', 1.45, 'papas.jpg'),
(85, 'Calabacitas', 1.55, 'calabacitas.jpg'),
(86, 'Brócoli', 1.75, 'brocoli.jpg'),
(87, 'Coliflor', 1.85, 'coliflor.jpg'),
(88, 'Espinacas', 1.95, 'espinacas.jpg'),
(89, 'Lechuga Romana', 1.65, 'lechuga_romana.jpg'),
(90, 'Tomates Cherry', 2.25, 'tomates_cherry.jpg'),
(91, 'Pepinos', 1.35, 'pepinos.jpg'),
(92, 'Manzanas Verdes', 2.45, 'manzanas_verdes.jpg'),
(93, 'Peras', 2.35, 'peras.jpg'),
(94, 'Plátanos', 1.25, 'platanos.jpg'),
(95, 'Uvas', 3.15, 'uvas.jpg'),
(96, 'Fresas', 3.45, 'fresas.jpg'),
(97, 'Mangos', 2.75, 'mangos.jpg'),
(98, 'Piñas', 3.25, 'pinas.jpg'),
(99, 'Sandías', 4.15, 'sandias.jpg'),
(100, 'Melones', 3.95, 'melones.jpg');